import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { User } from '../models/User.js';
import { StudentProfile } from '../models/StudentProfile.js';
import { EmployerProfile } from '../models/EmployerProfile.js';
import { Job } from '../models/Job.js';
import { Availability } from '../models/Availability.js';
import { MicroTask } from '../models/MicroTask.js';
import { Blog } from '../models/Blog.js';
import { Shift } from '../models/Shift.js';
import { Application } from '../models/Application.js';
import { Review } from '../models/Review.js';
import { EmployerVerification } from '../models/EmployerVerification.js';

dotenv.config();

const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/hoalacviec';

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('[Seed] Connected to MongoDB');

    // Clear existing data
    await Promise.all([
      User.deleteMany({}),
      StudentProfile.deleteMany({}),
      EmployerProfile.deleteMany({}),
      EmployerVerification.deleteMany({}),
      Job.deleteMany({}),
      Availability.deleteMany({}),
      MicroTask.deleteMany({}),
      Blog.deleteMany({}),
      Shift.deleteMany({}),
      Application.deleteMany({}),
      Review.deleteMany({}),
    ]);
    console.log('[Seed] Cleared existing collections');

    // 1. Users
    const studentUser = await User.create({
      name: 'Nguyễn Minh Khoa',
      email: 'khoa.nguyen@student.fpt.edu.vn',
      password: '123456',
      role: 'student',
      phone: '0981234567',
    });

    const studentUser2 = await User.create({
      name: 'Trần Thị Linh',
      email: 'linh.tran@student.fpt.edu.vn',
      password: '123456',
      role: 'student',
      phone: '0977654321',
    });

    const employerUser = await User.create({
      name: 'Café Xanh Hòa Lạc',
      email: 'cafexanh@hoalacviec.vn',
      password: '123456',
      role: 'employer',
      phone: '0901231001',
    });

    const employerUser2 = await User.create({
      name: 'Bách Hóa SV Market',
      email: 'svmarket@hoalacviec.vn',
      password: '123456',
      role: 'employer',
      phone: '0912342002',
    });

    const adminUser = await User.create({
      name: 'Admin Hoa Lạc Việc',
      email: 'admin@hoalacviec.vn',
      password: '123456',
      role: 'admin',
      phone: '0999999999',
    });

    // 2. Profiles
    const sp1 = await StudentProfile.create({
      userId: studentUser._id,
      university: 'Đại học FPT Hòa Lạc',
      studentCode: 'HE163456',
      yearOfStudy: 3,
      major: 'Kỹ thuật phần mềm',
      area: 'fpt_university',
      address: 'KTX Dom A - ĐH FPT Hòa Lạc',
      location: { lat: 21.0134, lng: 105.5263 },
      bio: 'Sinh viên FPT năm 3, cần tìm việc làm thêm ca chiều tối hoặc việc vặt quanh trường.',
      skills: ['Pha chế', 'Thu ngân', 'Giao tiếp tốt', 'Xe máy riêng'],
      transport: 'xe_may',
      reputationScore: 4.8,
    });

    await StudentProfile.create({
      userId: studentUser2._id,
      university: 'ĐHQGHN Hòa Lạc',
      studentCode: 'QH2023001',
      yearOfStudy: 2,
      major: 'Kinh tế đối ngoại',
      area: 'ktx_dhqg',
      address: 'KTX ĐHQG Hòa Lạc',
      location: { lat: 21.0060, lng: 105.5230 },
      skills: ['Thu ngân', 'Bán hàng', 'Nấu ăn', 'Tiếng Anh'],
      transport: 'xe_buyt',
      reputationScore: 4.9,
    });

    const ep1 = await EmployerProfile.create({
      userId: employerUser._id,
      storeName: 'Café Xanh Hòa Lạc',
      storeType: 'Quán cà phê',
      address: 'Tầng 1, Tòa A, KĐT FPT Hòa Lạc',
      area: 'fpt_university',
      location: { lat: 21.0128, lng: 105.5255 },
      contactPhone: '0901231001',
      verified: true,
      busRoutes: ['Bus 72', 'Bus 74'],
      description: 'Quán cà phê phục vụ sinh viên và giảng viên, giờ mở cửa 7h-22h.',
      rating: 4.8,
      ratingCount: 24,
    });

    const ep2 = await EmployerProfile.create({
      userId: employerUser2._id,
      storeName: 'Bách Hóa SV Market',
      storeType: 'Cửa hàng tiện lợi',
      address: 'Đường D1, Khu Công Nghệ Cao Hòa Lạc, Thạch Thất, Hà Nội',
      area: 'fpt_university',
      location: { lat: 21.0155, lng: 105.5290 },
      locationStatus: 'confirmed',
      locationSource: 'map_pin',
      locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
      geoPoint: { type: 'Point', coordinates: [105.5290, 21.0155] },
      contactPhone: '0912342002',
      verified: true,
      busRoutes: ['Bus 72'],
      description: 'Siêu thị mini phục vụ nhu cầu sinh hoạt của sinh viên Hòa Lạc.',
      rating: 4.5,
      ratingCount: 18,
    });

    await EmployerVerification.create([
      {
        employerUserId: employerUser._id,
        storeName: 'Café Xanh Hòa Lạc',
        legalName: 'Nguyễn Văn Cường',
        taxCode: '0108991234',
        idCardNumber: '001201004567',
        businessAddress: 'Tầng 1, Tòa A, KĐT FPT Hòa Lạc',
        contactPhone: '0901231001',
        status: 'approved',
        reviewedAt: new Date(),
      },
      {
        employerUserId: employerUser2._id,
        storeName: 'Bách Hóa SV Market',
        legalName: 'Lê Thị Thu Hà',
        taxCode: '0109123456',
        idCardNumber: '001202007890',
        businessAddress: 'Đường D1, Khu Công Nghệ Cao Hòa Lạc, Thạch Thất, Hà Nội',
        contactPhone: '0912342002',
        status: 'approved',
        reviewedAt: new Date(),
      },
    ]);

    // 3. Availability for student 1
    await Availability.create({
      userId: studentUser._id,
      slots: {
        mon: ['afternoon', 'evening'],
        tue: ['afternoon'],
        wed: ['afternoon', 'evening'],
        thu: ['evening'],
        fri: ['morning', 'afternoon', 'evening'],
        sat: ['morning', 'afternoon'],
        sun: ['evening'],
      }
    });

    // 4. Jobs
    const j1 = await Job.create({
      employerId: ep1._id,
      storeName: 'Café Xanh Hòa Lạc',
      title: 'Nhân Viên Pha Chế & Quầy Bar',
      type: 'shift',
      salaryAmount: 35000,
      salaryUnit: 'hour',
      area: 'fpt_university',
      address: 'Tầng 1, Tòa A, KĐT FPT Hòa Lạc (Cách KTX FPT 400m)',
      location: { lat: 21.0128, lng: 105.5255 },
      locationStatus: 'confirmed',
      locationSource: 'map_pin',
      locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
      geoPoint: { type: 'Point', coordinates: [105.5255, 21.0128] },
      schedule: [
        { dayOfWeek: 1, startTime: '14:00', endTime: '21:00', slot: 'afternoon' },
        { dayOfWeek: 3, startTime: '14:00', endTime: '21:00', slot: 'afternoon' },
        { dayOfWeek: 5, startTime: '17:00', endTime: '22:00', slot: 'evening' },
      ],
      slots: 2,
      description: 'Pha chế đồ uống, chuẩn bị nguyên liệu và phục vụ quầy bar thân thiện. Được đào tạo tay nghề miễn phí.',
      requirements: ['Không yêu cầu kinh nghiệm', 'Thân thiện, đúng giờ', 'Ưu tiên sinh viên FPT/ĐHQG'],
      benefits: ['Uống nước miễn phí tại ca', 'Thưởng chuyên cần tháng', 'Môi trường làm việc năng động'],
      busRoutes: ['Bus 72', 'Bus 74'],
      featured: true,
      status: 'approved',
      tags: ['pha_che', 'cafe', 'fpt'],
      contactPhone: '0901231001',
    });

    const j2 = await Job.create({
      employerId: ep2._id,
      storeName: 'Bách Hóa SV Market',
      title: 'Thu Ngân & Kiểm Soát Quầy Hàng',
      type: 'shift',
      salaryAmount: 32000,
      salaryUnit: 'hour',
      area: 'fpt_university',
      address: 'Đường D1, Khu Công Nghệ Cao Hòa Lạc, Thạch Thất, Hà Nội (Gần KTX FPT)',
      location: { lat: 21.0155, lng: 105.5290 },
      locationStatus: 'confirmed',
      locationSource: 'map_pin',
      locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
      geoPoint: { type: 'Point', coordinates: [105.5215, 21.0205] },
      schedule: [
        { dayOfWeek: 2, startTime: '13:00', endTime: '18:00', slot: 'afternoon' },
        { dayOfWeek: 4, startTime: '13:00', endTime: '18:00', slot: 'afternoon' },
        { dayOfWeek: 6, startTime: '08:00', endTime: '13:00', slot: 'morning' },
      ],
      slots: 2,
      description: 'Thanh toán hoá đơn tại quầy, kiểm tra tem giá và xếp hàng hóa ngăn nắp.',
      requirements: ['Trung thực, cẩn thận', 'Sử dụng máy tính cơ bản'],
      benefits: ['Giảm giá 15% khi mua đồ', 'Hỗ trợ ăn nhẹ giữa ca'],
      busRoutes: ['Bus 72'],
      featured: true,
      status: 'approved',
      tags: ['thu_ngan', 'sieu_thi'],
      contactPhone: '0912342002',
    });

    await Job.create({
      employerId: ep1._id,
      storeName: 'Highlands Coffee Hòa Lạc (Tân Xã)',
      title: 'Nhân Viên Phục Vụ Bán Thời Gian',
      type: 'part_time',
      salaryAmount: 28000,
      salaryUnit: 'hour',
      area: 'tan_xa',
      address: 'Đường Ven Hồ Tân Xã, Xã Tân Xã, Thạch Thất',
      location: { lat: 21.0205, lng: 105.5215 },
      locationStatus: 'legacy_unverified',
      locationSource: null,
      locationConfirmedAt: null,
      schedule: [
        { dayOfWeek: 6, startTime: '07:00', endTime: '12:00', slot: 'morning' },
        { dayOfWeek: 7, startTime: '14:00', endTime: '20:00', slot: 'afternoon' },
      ],
      slots: 3,
      description: 'Dọn bàn, bưng bê thức uống và hỗ trợ khách hàng cuối tuần.',
      requirements: ['Nhanh nhẹn, chăm chỉ'],
      benefits: ['Đồng phục miễn phí', 'Tips cuối tuần chia đều'],
      busRoutes: ['Bus 74'],
      featured: false,
      status: 'approved',
      tags: ['phuc_vu', 'highlands', 'tan_xa'],
      contactPhone: '0933445566',
    });

    // 20 Additional Jobs for searching and map exploration
    const addedJobs = await Job.insertMany([
      {
        employerId: ep1._id,
        storeName: 'Trà Sữa Mixue Tân Xã',
        title: 'Nhân Viên Pha Chế Trà Sữa & Kem',
        type: 'shift',
        salaryAmount: 28000,
        salaryUnit: 'hour',
        area: 'tan_xa',
        address: 'Số 48 Thôn 3, Tân Xã, Thạch Thất (Gần Cổng FPT)',
        location: { lat: 21.0178, lng: 105.5222 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5222, 21.0178] },
        schedule: [
          { dayOfWeek: 1, startTime: '17:00', endTime: '22:30', slot: 'evening' },
          { dayOfWeek: 3, startTime: '17:00', endTime: '22:30', slot: 'evening' },
          { dayOfWeek: 5, startTime: '17:00', endTime: '22:30', slot: 'evening' },
        ],
        slots: 2,
        description: 'Pha chế trà sữa, làm kem ốc quế, đứng quầy thu ngân và vệ sinh máy pha vào cuối ca.',
        requirements: ['Nhanh nhẹn, vui vẻ', 'Làm được ca tối'],
        benefits: ['Giảm giá 30% đồ uống', 'Thưởng doanh số ngày đông khách'],
        busRoutes: ['Bus 74'],
        featured: true,
        status: 'approved',
        tags: ['tra_sua', 'pha_che', 'mixue', 'tan_xa'],
        contactPhone: '0988112233',
      },
      {
        employerId: ep1._id,
        storeName: 'Highlands Coffee FPT Campus',
        title: 'Barista / Pha Chế Espresso Sáng',
        type: 'shift',
        salaryAmount: 32000,
        salaryUnit: 'hour',
        area: 'fpt_university',
        address: 'Tòa nhà Beta, ĐH FPT Hòa Lạc',
        location: { lat: 21.0135, lng: 105.5265 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5265, 21.0135] },
        schedule: [
          { dayOfWeek: 2, startTime: '07:00', endTime: '12:00', slot: 'morning' },
          { dayOfWeek: 4, startTime: '07:00', endTime: '12:00', slot: 'morning' },
        ],
        slots: 1,
        description: 'Vận hành máy pha cafe espresso, chuẩn bị trà sen vàng và đồ uống phục vụ cán bộ, sinh viên FPT.',
        requirements: ['Có kinh nghiệm pha chế cơ bản là lợi thế', 'Đúng giờ, chuyên nghiệp'],
        benefits: ['Hỗ trợ ăn sáng', 'Đào tạo chuẩn pha chế barista'],
        busRoutes: ['Bus 72', 'Bus 74'],
        featured: true,
        status: 'approved',
        tags: ['barista', 'cafe', 'fpt', 'highlands'],
        contactPhone: '0977223344',
      },
      {
        employerId: ep2._id,
        storeName: 'Phở Cồ Cổ Điển Hòa Lạc',
        title: 'Phụ Quán & Bưng Bê Ca Sáng',
        type: 'shift',
        salaryAmount: 30000,
        salaryUnit: 'hour',
        area: 'tan_xa',
        address: 'Số 15 Trục đường chính Tân Xã, Thạch Thất',
        location: { lat: 21.0185, lng: 105.5210 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5210, 21.0185] },
        schedule: [
          { dayOfWeek: 1, startTime: '06:00', endTime: '10:30', slot: 'morning' },
          { dayOfWeek: 2, startTime: '06:00', endTime: '10:30', slot: 'morning' },
          { dayOfWeek: 3, startTime: '06:00', endTime: '10:30', slot: 'morning' },
        ],
        slots: 2,
        description: 'Bưng phở cho khách, dọn dẹp bàn ghế và rửa bát bằng máy.',
        requirements: ['Sức khỏe tốt, chịu khó', 'Dậy sớm được'],
        benefits: ['Bao 1 bát phở bò đặc biệt ăn sáng miễn phí', 'Lương thanh toán tuần'],
        busRoutes: ['Bus 74'],
        featured: false,
        status: 'approved',
        tags: ['phu_quan', 'an_sang', 'tan_xa'],
        contactPhone: '0966334455',
      },
      {
        employerId: ep2._id,
        storeName: 'Circle K Khu CNC Hòa Lạc',
        title: 'Nhân Viên Bán Hàng & Thu Ngân Ca Đêm',
        type: 'shift',
        salaryAmount: 36000,
        salaryUnit: 'hour',
        area: 'fpt_software',
        address: 'Cổng F-Ville 1, Đường D1, Khu CNC Hòa Lạc',
        location: { lat: 21.0190, lng: 105.5335 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5335, 21.0190] },
        schedule: [
          { dayOfWeek: 5, startTime: '22:00', endTime: '06:00', slot: 'evening' },
          { dayOfWeek: 6, startTime: '22:00', endTime: '06:00', slot: 'evening' },
        ],
        slots: 2,
        description: 'Bán hàng, thu ngân, hâm nóng thức ăn nhanh và kiểm kê hàng hóa ca đêm.',
        requirements: ['Nam/Nữ từ 18 tuổi', 'Thật thà, trách nhiệm'],
        benefits: ['Phụ cấp ca đêm cao', 'Môi trường máy lạnh sạch sẽ an ninh'],
        busRoutes: ['Bus 72'],
        featured: true,
        status: 'approved',
        tags: ['circle_k', 'ca_dem', 'thu_ngan', 'fpt_software'],
        contactPhone: '0944556677',
      },
      {
        employerId: ep2._id,
        storeName: 'Cơm Thố Bách Khoa Tân Xã',
        title: 'Nhân Viên Chạy Bàn & Tiếp Thực Buổi Trưa',
        type: 'shift',
        salaryAmount: 27000,
        salaryUnit: 'hour',
        area: 'tan_xa',
        address: 'Thôn 3, Tân Xã (Cách trường FPT 300m)',
        location: { lat: 21.0170, lng: 105.5230 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5230, 21.0170] },
        schedule: [
          { dayOfWeek: 1, startTime: '11:00', endTime: '14:00', slot: 'morning' },
          { dayOfWeek: 2, startTime: '11:00', endTime: '14:00', slot: 'morning' },
          { dayOfWeek: 4, startTime: '11:00', endTime: '14:00', slot: 'morning' },
        ],
        slots: 3,
        description: 'Tiếp thực các món cơm thố ra bàn, xếp đồ uống và dọn đĩa sau giờ cao điểm trưa của sinh viên.',
        requirements: ['Nhanh nhẹn, biết việc', 'Làm được khung giờ trưa'],
        benefits: ['Bao cơm trưa no nê', 'Làm việc cùng bạn bè sinh viên'],
        busRoutes: ['Bus 74'],
        featured: false,
        status: 'approved',
        tags: ['com_tho', 'chay_ban', 'tan_xa', 'an_trua'],
        contactPhone: '0911223344',
      },
      {
        employerId: ep1._id,
        storeName: 'Billiard Club 99 Hòa Lạc',
        title: 'Nhân Viên Xếp Bi & Phục Vụ Bàn Bida',
        type: 'shift',
        salaryAmount: 28000,
        salaryUnit: 'hour',
        area: 'thach_hoa',
        address: 'Gần Ngã tư Hòa Lạc, Quốc lộ 21A, Thạch Hòa',
        location: { lat: 21.0085, lng: 105.5185 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5185, 21.0085] },
        schedule: [
          { dayOfWeek: 4, startTime: '18:00', endTime: '23:00', slot: 'evening' },
          { dayOfWeek: 6, startTime: '18:00', endTime: '23:00', slot: 'evening' },
          { dayOfWeek: 7, startTime: '14:00', endTime: '22:00', slot: 'afternoon' },
        ],
        slots: 2,
        description: 'Xếp bóng bida cho khách, ghi giờ tính tiền trên phần mềm và phục vụ nước ngọt.',
        requirements: ['Ngoại hình sáng, giao tiếp tốt', 'Ưu tiên biết chơi bida cơ bản'],
        benefits: ['Được chơi bida miễn phí ngoài giờ làm', 'Tiền tip giữ 100%'],
        busRoutes: ['Bus 72'],
        featured: false,
        status: 'approved',
        tags: ['bida', 'billiard', 'thach_hoa', 'ca_toi'],
        contactPhone: '0933557799',
      },
      {
        employerId: ep1._id,
        storeName: 'Tiệm Bánh Mì Chảo Dom C FPT',
        title: 'Phụ Bếp & Giao Đồ Ăn Nội Khu KTX',
        type: 'hourly',
        salaryAmount: 26000,
        salaryUnit: 'hour',
        area: 'fpt_university',
        address: 'Căng tin Dom C, ĐH FPT Hòa Lạc',
        location: { lat: 21.0142, lng: 105.5268 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5268, 21.0142] },
        schedule: [
          { dayOfWeek: 2, startTime: '17:30', endTime: '21:30', slot: 'evening' },
          { dayOfWeek: 4, startTime: '17:30', endTime: '21:30', slot: 'evening' },
        ],
        slots: 2,
        description: 'Chiên trứng, nướng bánh mì và mang đồ ăn lên các tầng phòng KTX cho các bạn sinh viên.',
        requirements: ['Sinh viên ở KTX FPT', 'Nhanh nhẹn, cẩn thận'],
        benefits: ['Hỗ trợ ăn tối tại quán', 'Làm việc ngay trong trường không cần đi xe'],
        busRoutes: ['Bus 72'],
        featured: false,
        status: 'approved',
        tags: ['banh_mi', 'phu_bep', 'ktx_fpt'],
        contactPhone: '0922446688',
      },
      {
        employerId: ep2._id,
        storeName: 'Gym & Fitness FitZone Hòa Lạc',
        title: 'Lễ Tân & Trực Phòng Tập Gym Ca Tối',
        type: 'shift',
        salaryAmount: 30000,
        salaryUnit: 'hour',
        area: 'fpt_university',
        address: 'Đường gom Km 29 Đại Lộ Thăng Long (Cạnh FPT)',
        location: { lat: 21.0165, lng: 105.5285 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5285, 21.0165] },
        schedule: [
          { dayOfWeek: 1, startTime: '16:30', endTime: '21:00', slot: 'evening' },
          { dayOfWeek: 3, startTime: '16:30', endTime: '21:00', slot: 'evening' },
          { dayOfWeek: 5, startTime: '16:30', endTime: '21:00', slot: 'evening' },
        ],
        slots: 1,
        description: 'Check-in thẻ hội viên tại quầy lễ tân, phát khăn tập và hỗ trợ giải đáp thông tin cho học viên.',
        requirements: ['Năng động, yêu thích thể thao thể hình', 'Giao tiếp tốt'],
        benefits: ['Tập gym & yoga miễn phí 100%', 'Môi trường làm việc năng động'],
        busRoutes: ['Bus 72'],
        featured: true,
        status: 'approved',
        tags: ['gym', 'le_tan', 'fitness', 'fpt'],
        contactPhone: '0988664422',
      },
      {
        employerId: ep2._id,
        storeName: 'Nhà Sách Tuổi Trẻ KTX ĐHQG',
        title: 'Nhân Viên Bán Sách & Văn Phòng Phẩm',
        type: 'part_time',
        salaryAmount: 25000,
        salaryUnit: 'hour',
        area: 'dhqg_dorm',
        address: 'Tầng 1 Tòa nhà Dịch vụ, KTX ĐHQGHN Hòa Lạc',
        location: { lat: 21.0048, lng: 105.5295 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5295, 21.0048] },
        schedule: [
          { dayOfWeek: 2, startTime: '13:00', endTime: '18:00', slot: 'afternoon' },
          { dayOfWeek: 4, startTime: '13:00', endTime: '18:00', slot: 'afternoon' },
          { dayOfWeek: 6, startTime: '08:00', endTime: '12:00', slot: 'morning' },
        ],
        slots: 2,
        description: 'Sắp xếp kệ sách, bán đồ dùng học tập giáo trình và photo tài liệu cho sinh viên ĐHQG.',
        requirements: ['Cẩn thận, tỉ mỉ', 'Ưu tiên sinh viên ĐHQG'],
        benefits: ['Được đọc sách mới miễn phí', 'Môi trường yên tĩnh vừa làm vừa học'],
        busRoutes: ['Bus 72'],
        featured: false,
        status: 'approved',
        tags: ['nha_sach', 'van_phong_pham', 'dhqg'],
        contactPhone: '0909112233',
      },
      {
        employerId: ep1._id,
        storeName: 'Aha Cafe Ven Hồ Tân Xã',
        title: 'Nhân Viên Phục Vụ Ca Tối Hóng Gió Hồ',
        type: 'shift',
        salaryAmount: 28000,
        salaryUnit: 'hour',
        area: 'tan_xa',
        address: 'Số 1 đường Ven Hồ Tân Xã, Thạch Thất',
        location: { lat: 21.0210, lng: 105.5218 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5218, 21.0210] },
        schedule: [
          { dayOfWeek: 5, startTime: '18:00', endTime: '23:00', slot: 'evening' },
          { dayOfWeek: 6, startTime: '18:00', endTime: '23:00', slot: 'evening' },
          { dayOfWeek: 7, startTime: '18:00', endTime: '23:00', slot: 'evening' },
        ],
        slots: 3,
        description: 'Order đồ uống tại bàn ven hồ, dọn cốc chén và giữ gìn cảnh quan quán sạch đẹp.',
        requirements: ['Tháo vát, thân thiện', 'Làm được các buổi tối cuối tuần'],
        benefits: ['Không gian ven hồ thoáng mát', 'Tips cao vào các đêm cuối tuần'],
        busRoutes: ['Bus 74'],
        featured: true,
        status: 'approved',
        tags: ['cafe', 'aha_cafe', 'tan_xa', 'ven_ho'],
        contactPhone: '0977889900',
      },
      {
        employerId: ep2._id,
        storeName: 'Bún Chả Nướng Than Hoa Thạch Hòa',
        title: 'Nướng Chả & Dọn Dẹp Giờ Trưa',
        type: 'shift',
        salaryAmount: 30000,
        salaryUnit: 'hour',
        area: 'thach_hoa',
        address: 'Gần cầu vượt Hòa Lạc, Quốc lộ 21, Thạch Hòa',
        location: { lat: 21.0092, lng: 105.5175 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5175, 21.0092] },
        schedule: [
          { dayOfWeek: 1, startTime: '10:30', endTime: '13:30', slot: 'morning' },
          { dayOfWeek: 3, startTime: '10:30', endTime: '13:30', slot: 'morning' },
          { dayOfWeek: 5, startTime: '10:30', endTime: '13:30', slot: 'morning' },
        ],
        slots: 2,
        description: 'Quạt chả nướng than hoa, chia bún và rau sống phục vụ khách ăn trưa.',
        requirements: ['Không ngại mùi khói bếp', 'Nhanh nhẹn'],
        benefits: ['Bao suất bún chả đặc biệt', 'Nhận lương theo ngày nếu muốn'],
        busRoutes: ['Bus 72'],
        featured: false,
        status: 'approved',
        tags: ['bun_cha', 'an_trua', 'thach_hoa'],
        contactPhone: '0966778899',
      },
      {
        employerId: ep1._id,
        storeName: 'Tiệm Giặt Sấy SpeedWash Tân Xã',
        title: 'Gấp Quần Áo & Trực Máy Giặt Sấy',
        type: 'part_time',
        salaryAmount: 25000,
        salaryUnit: 'hour',
        area: 'tan_xa',
        address: 'Thôn 2, Tân Xã (Cạnh ngõ trọ số 8)',
        location: { lat: 21.0168, lng: 105.5235 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5235, 21.0168] },
        schedule: [
          { dayOfWeek: 2, startTime: '16:00', endTime: '20:00', slot: 'afternoon' },
          { dayOfWeek: 4, startTime: '16:00', endTime: '20:00', slot: 'afternoon' },
        ],
        slots: 1,
        description: 'Bỏ quần áo vào máy giặt, chuyển sang máy sấy, gấp gọn gàng đóng túi cho sinh viên đến nhận.',
        requirements: ['Cẩn thận, sạch sẽ', 'Có thể ngồi học bài trong lúc chờ máy chạy'],
        benefits: ['Giặt sấy quần áo cá nhân miễn phí 100%', 'Công việc nhẹ nhàng'],
        busRoutes: ['Bus 74'],
        featured: false,
        status: 'approved',
        tags: ['giat_say', 'nhe_nhang', 'tan_xa'],
        contactPhone: '0912334455',
      },
      {
        employerId: ep2._id,
        storeName: 'Gà Rán Chimaek Hàn Quốc FPT',
        title: 'Thu Ngân & Đóng Hộp Món Ăn Ship',
        type: 'shift',
        salaryAmount: 29000,
        salaryUnit: 'hour',
        area: 'fpt_university',
        address: 'Kiot số 3 Cổng 1 ĐH FPT Hòa Lạc',
        location: { lat: 21.0130, lng: 105.5258 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5258, 21.0130] },
        schedule: [
          { dayOfWeek: 3, startTime: '17:00', endTime: '22:00', slot: 'evening' },
          { dayOfWeek: 5, startTime: '17:00', endTime: '22:00', slot: 'evening' },
          { dayOfWeek: 7, startTime: '17:00', endTime: '22:00', slot: 'evening' },
        ],
        slots: 2,
        description: 'Bấm máy thu ngân, nhận đơn từ shipper ShopeeFood/GrabFood và đóng hộp gà rán kèm sốt.',
        requirements: ['Nhanh tay, chính xác', 'Nhiệt tình với khách hàng'],
        benefits: ['Ăn gà rán thỏa thích trong ca', 'Thưởng doanh số cuối tháng'],
        busRoutes: ['Bus 72', 'Bus 74'],
        featured: true,
        status: 'approved',
        tags: ['ga_ran', 'thu_ngan', 'fpt', 'an_vat'],
        contactPhone: '0988990011',
      },
      {
        employerId: ep1._id,
        storeName: 'Cyber Gaming Arena Hòa Lạc',
        title: 'Trực Quầy Quán Nét & Pha Mì Ca Đêm',
        type: 'shift',
        salaryAmount: 26000,
        salaryUnit: 'hour',
        area: 'tan_xa',
        address: 'Số 99 Trục chính Tân Xã, Thạch Thất',
        location: { lat: 21.0180, lng: 105.5215 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5215, 21.0180] },
        schedule: [
          { dayOfWeek: 6, startTime: '22:30', endTime: '06:30', slot: 'evening' },
          { dayOfWeek: 7, startTime: '22:30', endTime: '06:30', slot: 'evening' },
        ],
        slots: 2,
        description: 'Nạp giờ chơi cho khách, pha mì tôm xúc xích, dọn bàn phím và lau màn hình.',
        requirements: ['Biết sử dụng máy tính tốt', 'Thức đêm tốt'],
        benefits: ['Chơi máy phòng VIP miễn phí sau ca', 'Bao ăn đêm'],
        busRoutes: ['Bus 74'],
        featured: false,
        status: 'approved',
        tags: ['quan_net', 'gaming', 'ca_dem', 'tan_xa'],
        contactPhone: '0933771122',
      },
      {
        employerId: ep2._id,
        storeName: 'Trà Chanh Bụi Phố KTX ĐHQG',
        title: 'Pha Chế Trà Chanh & Hướng Dẫn Khách',
        type: 'part_time',
        salaryAmount: 25000,
        salaryUnit: 'hour',
        area: 'dhqg_dorm',
        address: 'Cổng 2 Khu KTX ĐHQGHN Hòa Lạc',
        location: { lat: 21.0050, lng: 105.5300 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5300, 21.0050] },
        schedule: [
          { dayOfWeek: 1, startTime: '18:30', endTime: '22:30', slot: 'evening' },
          { dayOfWeek: 3, startTime: '18:30', endTime: '22:30', slot: 'evening' },
          { dayOfWeek: 5, startTime: '18:30', endTime: '22:30', slot: 'evening' },
        ],
        slots: 2,
        description: 'Pha trà tắc, trà đào, nước mía và mang hướng dương ra bàn cho sinh viên ngồi tán gẫu.',
        requirements: ['Nhanh nhẹn, vui tươi', 'Ưu tiên sinh viên nội khu'],
        benefits: ['Môi trường đông vui', 'Uống nước miễn phí'],
        busRoutes: ['Bus 72'],
        featured: false,
        status: 'approved',
        tags: ['tra_chanh', 'dhqg', 'sinh_vien'],
        contactPhone: '0944668800',
      },
      {
        employerId: ep1._id,
        storeName: 'Nhà Hàng Lẩu Nướng BBQ Tân Xã',
        title: 'Nhân Viên Tiếp Thực & Chạy Bàn Tiệc Tối',
        type: 'shift',
        salaryAmount: 32000,
        salaryUnit: 'hour',
        area: 'tan_xa',
        address: 'Đường liên thôn Tân Xã, Thạch Thất',
        location: { lat: 21.0192, lng: 105.5205 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5205, 21.0192] },
        schedule: [
          { dayOfWeek: 5, startTime: '17:00', endTime: '22:30', slot: 'evening' },
          { dayOfWeek: 6, startTime: '17:00', endTime: '22:30', slot: 'evening' },
          { dayOfWeek: 7, startTime: '17:00', endTime: '22:30', slot: 'evening' },
        ],
        slots: 4,
        description: 'Thay vỉ nướng, châm than, bưng đồ ăn lẩu nướng ra bàn và hỗ trợ dọn dẹp kết ca.',
        requirements: ['Nhanh nhẹn, chịu khó', 'Chịu được áp lực giờ đông khách'],
        benefits: ['Bao bữa ăn tối lẩu nướng thơm ngon', 'Thưởng tip theo bàn'],
        busRoutes: ['Bus 74'],
        featured: true,
        status: 'approved',
        tags: ['lau_nuong', 'bbq', 'tan_xa', 'tiep_thuc'],
        contactPhone: '0966113355',
      },
      {
        employerId: ep2._id,
        storeName: 'Cửa Hàng Tiện Lợi 7-Eleven F-Ville 3',
        title: 'Nhân Viên Bán Hàng Ca Sáng & Trưa',
        type: 'shift',
        salaryAmount: 33000,
        salaryUnit: 'hour',
        area: 'fpt_software',
        address: 'Khu công nghệ cao Hòa Lạc, F-Ville 3',
        location: { lat: 21.0215, lng: 105.5380 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5380, 21.0215] },
        schedule: [
          { dayOfWeek: 1, startTime: '07:30', endTime: '13:30', slot: 'morning' },
          { dayOfWeek: 3, startTime: '07:30', endTime: '13:30', slot: 'morning' },
        ],
        slots: 2,
        description: 'Bán hàng tiện lợi, sắp xếp kệ bánh kẹo nước ngọt phục vụ lập trình viên và kỹ sư FPT.',
        requirements: ['Giao tiếp văn minh lịch sự', 'Có trách nhiệm'],
        benefits: ['Môi trường tòa nhà công nghệ cao hiện đại', 'Có máy điều hòa mát mẻ'],
        busRoutes: ['Bus 72'],
        featured: false,
        status: 'approved',
        tags: ['tien_loi', 'fpt_software', 'fville3'],
        contactPhone: '0977114477',
      },
      {
        employerId: ep1._id,
        storeName: 'Lớp Học Gia Sư Trí Tuệ Hòa Lạc',
        title: 'Gia Sư Dạy Kèm Toán & Tiếng Anh Lớp 6 - 8',
        type: 'hourly',
        salaryAmount: 60000,
        salaryUnit: 'hour',
        area: 'thach_hoa',
        address: 'Khu dân cư Thạch Hòa, gần Chợ Hòa Lạc',
        location: { lat: 21.0075, lng: 105.5190 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5190, 21.0075] },
        schedule: [
          { dayOfWeek: 2, startTime: '18:00', endTime: '20:00', slot: 'evening' },
          { dayOfWeek: 4, startTime: '18:00', endTime: '20:00', slot: 'evening' },
        ],
        slots: 2,
        description: 'Kèm cặp bài vở môn Toán và Tiếng Anh cơ bản cho 2 em học sinh cấp 2 gần trường FPT.',
        requirements: ['Sinh viên FPT/ĐHQG điểm thi đại học tốt', 'Kiên nhẫn, nhiệt tình giảng giải'],
        benefits: ['Mức lương cao 120k/buổi 2 tiếng', 'Phụ huynh tâm lý, hỗ trợ trà bánh'],
        busRoutes: ['Bus 72'],
        featured: true,
        status: 'approved',
        tags: ['gia_su', 'day_kem', 'tieng_anh', 'toan'],
        contactPhone: '0988335577',
      },
      {
        employerId: ep2._id,
        storeName: 'Bưu Cục J&T Express Hòa Lạc',
        title: 'Nhân Viên Phân Loại Bưu Kiện Hàng Shopee',
        type: 'shift',
        salaryAmount: 35000,
        salaryUnit: 'hour',
        area: 'fpt_software',
        address: 'Trục đường ĐT 419, Thạch Thất (Cách Khu CNC 1km)',
        location: { lat: 21.0160, lng: 105.5320 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5320, 21.0160] },
        schedule: [
          { dayOfWeek: 2, startTime: '17:30', endTime: '21:30', slot: 'evening' },
          { dayOfWeek: 4, startTime: '17:30', endTime: '21:30', slot: 'evening' },
          { dayOfWeek: 6, startTime: '17:30', endTime: '21:30', slot: 'evening' },
        ],
        slots: 3,
        description: 'Bắn mã vạch quét bưu kiện, phân loại hàng hóa vào các bao tải theo từng tuyến giao.',
        requirements: ['Chăm chỉ, khỏe khoắn', 'Không yêu cầu kinh nghiệm'],
        benefits: ['Lương tính chuẩn theo giờ, nhận hàng tuần', 'Phù hợp bạn nam sinh viên'],
        busRoutes: ['Bus 72', 'Bus 74'],
        featured: false,
        status: 'approved',
        tags: ['kho_hang', 'shopee', 'boc_xep', 'fpt_software'],
        contactPhone: '0901889922',
      },
      {
        employerId: ep1._id,
        storeName: 'Hair Salon & Spa Thảo Mộc Tân Xã',
        title: 'Lễ Tân & Phụ Gội Đầu Dưỡng Sinh',
        type: 'part_time',
        salaryAmount: 28000,
        salaryUnit: 'hour',
        area: 'tan_xa',
        address: 'Đường vào thôn 3, Tân Xã, Thạch Thất',
        location: { lat: 21.0172, lng: 105.5228 },
        locationStatus: 'confirmed',
        locationSource: 'map_pin',
        locationConfirmedAt: new Date('2026-09-19T10:00:00Z'),
        geoPoint: { type: 'Point', coordinates: [105.5228, 21.0172] },
        schedule: [
          { dayOfWeek: 3, startTime: '14:00', endTime: '19:00', slot: 'afternoon' },
          { dayOfWeek: 6, startTime: '14:00', endTime: '19:00', slot: 'afternoon' },
          { dayOfWeek: 7, startTime: '09:00', endTime: '17:00', slot: 'morning' },
        ],
        slots: 2,
        description: 'Đón khách, sấy tóc nhẹ nhàng và phụ gội đầu thảo dược dưỡng sinh.',
        requirements: ['Nữ sinh viên khéo tay, nhẹ nhàng', 'Được tiệm đào tạo bài bản'],
        benefits: ['Chăm sóc tóc và da miễn phí', 'Tip từ khách nhận trọn vẹn'],
        busRoutes: ['Bus 74'],
        featured: false,
        status: 'approved',
        tags: ['spa', 'salon', 'goi_dau', 'tan_xa'],
        contactPhone: '0933221188',
      }
    ]);

    // 5. Micro-tasks (Thuê việc vặt sinh viên Hòa Lạc)
    await MicroTask.create([
      {
        title: 'Nhờ đi chợ mua rau củ & đồ ăn nấu cơm trưa',
        category: 'di_cho',
        description: 'Mình bận làm đồ án kỳ này, cần bạn đi chợ Tân Xã mua ít thịt nạc, rau ngót và trứng mang lên phòng KTX Dom A.',
        reward: 40000,
        location: 'KTX Dom A - ĐH FPT Hòa Lạc',
        deadline: 'Trước 11:30 trưa nay',
        requesterId: studentUser._id,
        requesterName: 'Nguyễn Minh Khoa',
        requesterPhone: '0981234567',
        status: 'open',
      },
      {
        title: 'Cần xe ôm sinh viên chở từ FPT sang KTX ĐHQG Hòa Lạc',
        category: 'xe_om',
        description: 'Mình có xe đạp bị hỏng, cần bạn sinh viên có xe máy chở mình và balo đồ sang KTX ĐHQG.',
        reward: 35000,
        location: 'Cổng trường FPT Hòa Lạc -> KTX ĐHQG',
        deadline: '17:00 chiều nay',
        requesterId: studentUser2._id,
        requesterName: 'Trần Thị Linh',
        requesterPhone: '0977654321',
        status: 'open',
      },
      {
        title: 'Lấy hộ thùng hàng Shopee tại bốt bảo vệ cổng 1',
        category: 'lay_ship',
        description: 'Shipper giao kiện hàng to (khoảng 3kg), mình đang trên giảng đường Alpha không xuống được. Nhờ bạn lấy hộ để tại bàn lễ tân KTX Dom C.',
        reward: 25000,
        location: 'Cổng 1 ĐH FPT Hòa Lạc',
        deadline: 'Trong 1 giờ tới',
        requesterId: studentUser._id,
        requesterName: 'Nguyễn Minh Khoa',
        requesterPhone: '0981234567',
        status: 'accepted',
        assigneeId: studentUser2._id,
        assigneeName: 'Trần Thị Linh',
        assigneePhone: '0977654321',
        note: 'Đang chạy qua lấy hộ bạn đây nhé!',
      },
      {
        title: 'Nhờ bưng đồ chuyển trọ từ Tân Xã về ký túc xá',
        category: 'chuyen_do',
        description: 'Cần 1 bạn nam khỏe mạnh phụ bưng 2 thùng sách và 1 vali từ nhà trọ ngõ 12 Tân Xã lên xe ba gác.',
        reward: 80000,
        location: 'Ngõ 12 Hồ Tân Xã',
        deadline: 'Sáng mai (Thứ 7)',
        requesterId: studentUser2._id,
        requesterName: 'Trần Thị Linh',
        requesterPhone: '0977654321',
        status: 'open',
      },
      {
        title: 'Cần bạn nấu bữa tối hộ cho phòng 4 người',
        category: 'nau_an',
        description: 'Phòng mình cả 4 đứa đều ôn thi đến tối muộn, thực phẩm đã mua sẵn trong tủ lạnh, cần 1 bạn qua nấu giúp 3 món đơn giản (thịt kho, canh rau ngót, trứng rán) và cắm cơm.',
        reward: 70000,
        location: 'Phòng 302 Nhà trọ BlueHouse Tân Xã',
        deadline: '18:30 tối nay',
        requesterId: studentUser._id,
        requesterName: 'Nguyễn Minh Khoa',
        requesterPhone: '0981234567',
        status: 'open',
      },
      {
        title: 'Photo & đóng bìa mềm tập đồ án tốt nghiệp',
        category: 'khac',
        description: 'Mình gửi file PDF qua Zalo, nhờ bạn in 3 bản A4 2 mặt và đóng gáy xoắn tại quán Photo Dom B rồi mang sang sảnh tòa Gamma.',
        reward: 30000,
        location: 'Quán Photo Dom B ĐH FPT Hòa Lạc',
        deadline: 'Trước 15:00 hôm nay',
        requesterId: studentUser2._id,
        requesterName: 'Trần Thị Linh',
        requesterPhone: '0977654321',
        status: 'open',
      },
      {
        title: 'Chở người ốm đi khám tại Trạm y tế Thạch Hòa',
        category: 'xe_om',
        description: 'Bạn cùng phòng mình bị sốt siêu vi, cần bạn có xe máy và mũ bảo hiểm chở bạn ấy sang Trạm Y tế xã Thạch Hòa rồi chở về.',
        reward: 50000,
        location: 'KTX Dom F -> Trạm y tế Thạch Hòa',
        deadline: 'Càng sớm càng tốt',
        requesterId: studentUser._id,
        requesterName: 'Nguyễn Minh Khoa',
        requesterPhone: '0981234567',
        status: 'completed',
        assigneeId: studentUser2._id,
        assigneeName: 'Trần Thị Linh',
        assigneePhone: '0977654321',
      },
      {
        title: 'Nhờ vác 2 bình nước Lavie 20L lên tầng 4 Dom D',
        category: 'chuyen_do',
        description: 'Thang máy KTX đang bảo trì 30 phút, cần bạn nam giúp bưng 2 bình nước từ sảnh lễ tân lên phòng 412 Dom D.',
        reward: 30000,
        location: 'Sảnh KTX Dom D - ĐH FPT',
        deadline: 'Trong chiều nay',
        requesterId: studentUser2._id,
        requesterName: 'Trần Thị Linh',
        requesterPhone: '0977654321',
        status: 'open',
      },
      {
        title: 'Đón nhận đồ gửi theo xe buýt 74 tại bến xe FPT',
        category: 'lay_ship',
        description: 'Mẹ mình gửi túi đồ ăn quê theo phụ xe buýt 74 (biển số 29B-12345), dự kiến đến bến xe FPT lúc 16h45. Nhờ bạn ra nhận hộ.',
        reward: 35000,
        location: 'Điểm dừng xe buýt Cổng ĐH FPT Hòa Lạc',
        deadline: '16:45 hôm nay',
        requesterId: studentUser._id,
        requesterName: 'Nguyễn Minh Khoa',
        requesterPhone: '0981234567',
        status: 'open',
      },
      {
        title: 'Đi chợ Hòa Lạc mua cá chép giòn và rau lẩu',
        category: 'di_cho',
        description: 'Cần bạn quen đi chợ Hòa Lạc chọn mua 1 con cá chép giòn làm sạch sẵn, 1kg nấm kim châm và rau muống cho tiệc sinh nhật tối nay.',
        reward: 60000,
        location: 'Chợ Hòa Lạc, Km 29 Đại Lộ Thăng Long',
        deadline: 'Trước 16:30 chiều nay',
        requesterId: studentUser2._id,
        requesterName: 'Trần Thị Linh',
        requesterPhone: '0977654321',
        status: 'open',
      },
      {
        title: 'Đem xe máy đi vá xăm và thay dầu máy tại tiệm Tân Xã',
        category: 'khac',
        description: 'Xe Wave Alpha của mình bị đinh non ở bánh sau, để ở bãi xe Dom E. Cần bạn dắt/chở ra quán sửa xe Tân Xã vá và thay nhớt (tiền sửa mình thanh toán riêng).',
        reward: 45000,
        location: 'Bãi xe KTX Dom E ĐH FPT',
        deadline: 'Trước 18:00',
        requesterId: studentUser._id,
        requesterName: 'Nguyễn Minh Khoa',
        requesterPhone: '0981234567',
        status: 'open',
      },
      {
        title: 'Hỗ trợ dọn dẹp và quét dọn phòng trọ trước khi trả phòng',
        category: 'chuyen_do',
        description: 'Mình chuyển trọ sang KTX, cần 1 bạn phụ dọn rác, lau sàn và cọ nhà vệ sinh phòng 25m2.',
        reward: 90000,
        location: 'Xóm 2 Thôn 4, Tân Xã, Thạch Thất',
        deadline: 'Chủ Nhật tuần này',
        requesterId: studentUser2._id,
        requesterName: 'Trần Thị Linh',
        requesterPhone: '0977654321',
        status: 'open',
      },
      {
        title: 'Nhờ bạn chăm và cho 2 chú mèo ăn trong 2 ngày về quê',
        category: 'khac',
        description: 'Mình về quê Hải Phòng 2 ngày cuối tuần, cần bạn yêu mèo ghé phòng 1 lần/ngày lúc 19h để châm hạt, thay nước và dọn cát vệ sinh.',
        reward: 80000,
        location: 'Khu trọ Sinh Viên Xanh, Thạch Hòa',
        deadline: 'Thứ Bảy và Chủ Nhật',
        requesterId: studentUser._id,
        requesterName: 'Nguyễn Minh Khoa',
        requesterPhone: '0981234567',
        status: 'open',
      },
      {
        title: 'Ship hộp cơm trưa từ Căn tin Dom B sang Tòa nhà Beta',
        category: 'di_cho',
        description: 'Trời đang mưa to, mình đang họp nhóm tại phòng Lab 304 Beta. Nhờ bạn lấy hộp cơm sườn đã đặt sẵn ở Căn tin mang qua sảnh Beta giúp.',
        reward: 25000,
        location: 'Căn tin Dom B -> Sảnh Tòa Beta ĐH FPT',
        deadline: '12:15 trưa nay',
        requesterId: studentUser2._id,
        requesterName: 'Trần Thị Linh',
        requesterPhone: '0977654321',
        status: 'completed',
        assigneeId: studentUser._id,
        assigneeName: 'Nguyễn Minh Khoa',
        assigneePhone: '0981234567',
      }
    ]);

    // 6. Blogs
    await Blog.create([
      {
        title: 'Cẩm Nang Tìm Việc Part-time Cho Tân Sinh Viên Lên Hòa Lạc',
        slug: 'cam-nang-tim-viec-part-time-hoa-lac',
        summary: 'Khu công nghệ cao Hòa Lạc rộng lớn và có những đặc thù riêng. Cùng khám phá các khu vực tập trung nhiều việc làm thêm phù hợp với sinh viên.',
        content: `Khi mới chuyển lên Hòa Lạc học tập tại Đại học FPT, ĐHQGHN hay BKHN, nhiều bạn sinh viên mong muốn tìm kiếm một công việc làm thêm để trang trải sinh hoạt phí và tích lũy trải nghiệm sống.

### 1. Khu vực tập trung nhiều việc làm
- **Nội khu trường & KTX:** Các quán cà phê, căn tin, cửa hàng tiện lợi nội khu. Ưu điểm là gần, đi bộ được và giờ giấc thân thiện với sinh viên.
- **Khu vực Tân Xã:** Nằm sát hồ Tân Xã, tập trung rất nhiều quán trà sữa, quán ăn vặt, quán nhậu sinh viên, tiệm nét.
- **Khu CNC Hòa Lạc:** Các toà nhà văn phòng (F-Ville 1, F-Ville 2, Viettel) thường có các đơn vị dịch vụ F&B, bảo vệ, sự kiện.

### 2. Bí quyết sắp xếp thời gian
Lịch học tại FPT và ĐHQG thường chia theo slot hoặc block. Hãy ưu tiên đăng ký lịch rảnh cố định để chủ quán dễ dàng sắp ca, tránh đăng ký bừa bãi rồi nghỉ ngang ảnh hưởng tới điểm uy tín của bạn!`,
        category: 'cam_nang',
        coverImage: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&auto=format&fit=crop&q=60',
        author: { name: 'Ban Biên Tập Hoa Lạc Việc', role: 'Cố vấn sinh viên' },
        tags: ['hoa_lac', 'tan_sinh_vien', 'part_time'],
        featured: true,
      },
      {
        title: 'Cảnh Giác 4 Bẫy Lừa Đảo Việc Làm Thêm Sinh Viên Thường Gặp',
        slug: 'canh-giac-lua-dao-viec-lam-sinh-vien',
        summary: 'Các chiêu trò thu phí đồng phục, cọc tiền giữ chân, việc nhẹ lương cao online... Những dấu hiệu nhận biết để bảo vệ túi tiền của bạn.',
        content: `Rất nhiều sinh viên năm nhất bị mất tiền oan vì các hội nhóm tuyển dụng không uy tín trên mạng xã hội. Dưới đây là những dấu hiệu bạn cần hết sức cảnh giác:

1. **Bắt đóng tiền cọc, tiền đồng phục hoặc phí hồ sơ:** Mọi nhà tuyển dụng chân chính KHÔNG BAO GIỜ thu tiền của ứng viên trước khi vào làm.
2. **"Việc nhẹ lương 500k/ngày chỉ cần gõ văn bản/bấm like Shopee":** 100% là bẫy lừa đảo nạp tiền làm nhiệm vụ.
3. **Địa điểm phỏng vấn mờ ám:** Hẹn phỏng vấn tại phòng trọ kín hoặc quán nước vỉa hè thay vì tại cửa hàng/văn phòng thật.
4. **Không có thông tin xác thực:** Hãy ưu tiên tìm việc trên nền tảng **Hoa Lạc Việc** vì mọi cửa hàng đều được định vị và xác thực rõ ràng.`,
        category: 'canh_bao',
        coverImage: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=60',
        author: { name: 'Tổ Trợ Giúp Pháp Lý Sinh Viên', role: 'Admin' },
        tags: ['canh_bao', 'an_toan', 'kinh_nghiem'],
        featured: true,
      },
      {
        title: 'Mô Hình Thuê Việc Vặt: Sinh Viên Hòa Lạc Giúp Nhau Cùng Có Lợi',
        slug: 'mo-hinh-thue-viec-vat-hoa-lac',
        summary: 'Tính năng Chợ việc vặt mới ra mắt trên Hoa Lạc Việc giúp giải quyết các nhu cầu cấp bách: đi chợ hộ, xe ôm nội khu, lấy bưu phẩm...',
        content: `Tại Hòa Lạc, khoảng cách giữa các khu KTX và chợ Tân Xã hay các toà nhà học tập khá xa. Không phải bạn sinh viên nào cũng có xe máy cá nhân.

Chợ việc vặt ra đời như một giải pháp cộng đồng:
- **Người cần:** Đang ốm, bận ôn thi, không có xe máy -> Chỉ cần đăng việc với khoản thù lao từ 20k - 50k.
- **Người làm:** Các bạn có xe máy hoặc có giờ rảnh -> Nhận việc kiếm thêm tiền ăn trưa, tiền xăng ngay lập tức.
- **Minh bạch:** Có thông tin số điện thoại, tài khoản xác thực sinh viên của trường.`,
        category: 'kinh_nghiem',
        coverImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop&q=60',
        author: { name: 'Nguyễn Minh Khoa', role: 'Sinh viên FPT K16' },
        tags: ['viec_vat', 'sinh_vien', 'cong_dong'],
        featured: false,
      },
      {
        title: 'Cẩm Nang Tuyến Xe Buýt 74, 88, 107, 72 Di Chuyển Lên Hòa Lạc',
        slug: 'cam-nang-xe-buyt-hoa-lac',
        summary: 'Tổng hợp chi tiết lộ trình, tần suất, giờ xuất bến các tuyến xe buýt công cộng kết nối trung tâm Hà Nội với Khu công nghệ cao Hòa Lạc.',
        content: `Hệ thống xe buýt công cộng tại Hòa Lạc ngày càng hoàn thiện, giúp sinh viên di chuyển tiết kiệm và thuận tiện:

- **Bus 74:** Bến xe Mỹ Đình ⇄ Xuân Khanh (dừng trực tiếp tại Cổng ĐH FPT và KTX ĐHQG). Tần suất 10 - 15 phút/chuyến. Giá vé 9.000đ.
- **Bus 107:** Kim Mã ⇄ Làng Văn Hóa Các Dân Tộc (chạy cao tốc Thăng Long, dừng tại trạm trung chuyển Hòa Lạc).
- **Bus 88:** Bến xe Mỹ Đình ⇄ Xuân Mai (qua ngã tư Hòa Lạc).
- **Bus 72:** Bến xe Yên Nghĩa ⇄ Xuân Mai (thuận tiện cho các bạn khu vực Hà Đông).

Mẹo nhỏ: Hãy làm vé tháng liên tuyến sinh viên để tiết kiệm tối đa chi phí đi lại giữa trường và nhà!`,
        category: 'cam_nang',
        coverImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&auto=format&fit=crop&q=60',
        author: { name: 'Ban Biên Tập Hoa Lạc Việc', role: 'Cố vấn sinh viên' },
        tags: ['xe_buyt', 'bus74', 'bus107', 'hoa_lac'],
        featured: true,
      },
      {
        title: 'Bí Quyết Cân Bằng Giữa Lịch Học FPT/ĐHQG Và Đi Làm Thêm Ca Tối',
        slug: 'can-bang-hoc-va-lam-them-hoa-lac',
        summary: 'Đi làm thêm mang lại thu nhập và kinh nghiệm quý giá, nhưng điểm GPA vẫn là ưu tiên hàng đầu. Cách phân bổ thời gian thông minh.',
        content: `Rất nhiều bạn sinh viên rơi vào tình trạng quá tải, thiếu ngủ dẫn đến trượt môn khi bắt đầu đi làm thêm. Dưới đây là những nguyên tắc giúp bạn luôn giữ thế chủ động:

1. **Giới hạn số giờ làm:** Tối đa 20 - 24 giờ/tuần (khoảng 3 - 4 ca làm).
2. **Ưu tiên ca làm gần phòng trọ/KTX:** Giảm thiểu thời gian di chuyển trong đêm lạnh mùa đông Hòa Lạc.
3. **Báo trước với quản lý lịch thi trước 2 tuần:** Các chủ cửa hàng trên Hoa Lạc Việc đều cam kết hỗ trợ sinh viên đổi ca trong các tuần thi cử.
4. **Tận dụng tính năng Khớp lịch học:** Trước khi ứng tuyển bất kỳ việc nào, hãy xem % Khớp lịch để tránh tuyệt đối các ca trùng với giờ lên lớp.`,
        category: 'kinh_nghiem',
        coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&auto=format&fit=crop&q=60',
        author: { name: 'Trần Thị Linh', role: 'Sinh viên ĐHQG' },
        tags: ['can_bang', 'hoc_tap', 'kinh_nghiem'],
        featured: false,
      },
      {
        title: 'Top 5 Tiêu Chí Chọn Việc Làm Part-Time Uy Tín Khu Vực Thạch Thất',
        slug: 'tieu-chi-chon-viec-lam-uy-tin-thach-that',
        summary: 'Làm thế nào để chọn được nơi làm việc minh bạch, trả lương đúng hẹn và đối xử công bằng với sinh viên?',
        content: `Để có một trải nghiệm làm thêm tích cực, hãy lưu ý 5 tiêu chí vàng sau:

1. **Cửa hàng đã được Admin xác thực:** Có huy hiệu xác minh màu xanh trên nền tảng Hoa Lạc Việc.
2. **Mức lương theo giờ rõ ràng:** Dao động từ 25.000đ - 45.000đ/giờ tùy vị trí và kỹ năng.
3. **Có lịch làm việc cố định theo tuần:** Giúp bạn chủ động sắp xếp thời gian làm bài tập lớn.
4. **Khoảng cách di chuyển hợp lý:** Bán kính dưới 3km tính từ trường học hoặc trọ.
5. **Có đánh giá tốt từ các sinh viên khóa trước:** Đọc kỹ phần nhận xét và sao đánh giá của cửa hàng trước khi nộp hồ sơ.`,
        category: 'cam_nang',
        coverImage: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&auto=format&fit=crop&q=60',
        author: { name: 'Ban Biên Tập Hoa Lạc Việc', role: 'Cố vấn tuyển dụng' },
        tags: ['uy_tin', 'tieu_chi', 'tim_viec'],
        featured: false,
      }
    ]);

    // 7. Shifts (Lịch ca làm việc)
    const todayStr = new Date().toISOString().split('T')[0];
    const yesterdayStr = new Date(Date.now() - 86400000).toISOString().split('T')[0];
    const tomorrowStr = new Date(Date.now() + 86400000).toISOString().split('T')[0];
    const dayAfterStr = new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0];

    await Shift.create([
      {
        jobId: j1._id,
        storeName: 'Café Xanh Hòa Lạc',
        employerId: employerUser._id,
        studentId: studentUser._id,
        studentName: 'Nguyễn Minh Khoa',
        role: 'Nhân viên pha chế',
        date: todayStr,
        startTime: '14:00',
        endTime: '21:00',
        hours: 7,
        wageRate: 35000,
        status: 'checked_in',
        attendance: {
          checkInAt: new Date(Date.now() - 3600000),
          locationVerified: true,
        }
      },
      {
        jobId: j1._id,
        storeName: 'Café Xanh Hòa Lạc',
        employerId: employerUser._id,
        studentId: studentUser._id,
        studentName: 'Nguyễn Minh Khoa',
        role: 'Nhân viên pha chế',
        date: yesterdayStr,
        startTime: '14:00',
        endTime: '21:00',
        hours: 7,
        wageRate: 35000,
        status: 'completed',
        attendance: {
          checkInAt: new Date(Date.now() - 86400000 - 3600000 * 7),
          checkOutAt: new Date(Date.now() - 86400000),
          locationVerified: true,
        }
      },
      {
        jobId: j1._id,
        storeName: 'Café Xanh Hòa Lạc',
        employerId: employerUser._id,
        studentId: studentUser._id,
        studentName: 'Nguyễn Minh Khoa',
        role: 'Nhân viên pha chế',
        date: tomorrowStr,
        startTime: '17:00',
        endTime: '22:00',
        hours: 5,
        wageRate: 35000,
        status: 'scheduled',
      },
      {
        jobId: j2._id,
        storeName: 'Bách Hóa SV Market',
        employerId: employerUser2._id,
        studentId: studentUser._id,
        studentName: 'Nguyễn Minh Khoa',
        role: 'Thu ngân quầy hàng',
        date: dayAfterStr,
        startTime: '08:00',
        endTime: '13:00',
        hours: 5,
        wageRate: 32000,
        status: 'scheduled',
      },
      {
        jobId: j2._id,
        storeName: 'Bách Hóa SV Market',
        employerId: employerUser2._id,
        studentId: studentUser2._id,
        studentName: 'Trần Thị Linh',
        role: 'Thu ngân & Soát đồ',
        date: todayStr,
        startTime: '13:00',
        endTime: '18:00',
        hours: 5,
        wageRate: 32000,
        status: 'scheduled',
      },
      {
        jobId: j2._id,
        storeName: 'Bách Hóa SV Market',
        employerId: employerUser2._id,
        studentId: studentUser2._id,
        studentName: 'Trần Thị Linh',
        role: 'Thu ngân & Soát đồ',
        date: yesterdayStr,
        startTime: '13:00',
        endTime: '18:00',
        hours: 5,
        wageRate: 32000,
        status: 'completed',
        attendance: {
          checkInAt: new Date(Date.now() - 86400000 - 3600000 * 5),
          checkOutAt: new Date(Date.now() - 86400000),
          locationVerified: true,
        }
      },
      {
        jobId: addedJobs[0]._id,
        storeName: 'Trà Sữa Mixue Tân Xã',
        employerId: employerUser._id,
        studentId: studentUser2._id,
        studentName: 'Trần Thị Linh',
        role: 'Pha chế kem & trà sữa',
        date: tomorrowStr,
        startTime: '18:00',
        endTime: '22:30',
        hours: 4.5,
        wageRate: 28000,
        status: 'scheduled',
      },
      {
        jobId: addedJobs[2]._id,
        storeName: 'Circle K Hòa Lạc',
        employerId: employerUser2._id,
        studentId: studentUser._id,
        studentName: 'Nguyễn Minh Khoa',
        role: 'Bán hàng ca đêm',
        date: dayAfterStr,
        startTime: '22:00',
        endTime: '06:00',
        hours: 8,
        wageRate: 32000,
        status: 'scheduled',
      }
    ]);

    // 8. Applications (Đơn ứng tuyển)
    await Application.create([
      {
        studentId: studentUser._id,
        studentName: 'Nguyễn Minh Khoa',
        studentPhone: '0981234567',
        studentEmail: 'khoa.nguyen@student.fpt.edu.vn',
        jobId: j1._id,
        employerId: employerUser._id,
        status: 'accepted',
        note: 'Em có thể làm các ca chiều thứ 2 và thứ 4.',
        employerNote: 'Nhận ca chiều. Đúng giờ nhé em.',
      },
      {
        studentId: studentUser._id,
        studentName: 'Nguyễn Minh Khoa',
        studentPhone: '0981234567',
        studentEmail: 'khoa.nguyen@student.fpt.edu.vn',
        jobId: j2._id,
        employerId: employerUser2._id,
        status: 'accepted',
        note: 'Em có xe máy riêng đi lại thuận tiện, có kinh nghiệm thu ngân siêu thị.',
        employerNote: 'Hồ sơ tốt, mời em đến nhận ca sáng thứ Bảy.',
      },
      {
        studentId: studentUser._id,
        studentName: 'Nguyễn Minh Khoa',
        studentPhone: '0981234567',
        studentEmail: 'khoa.nguyen@student.fpt.edu.vn',
        jobId: addedJobs[0]._id, // Mixue
        employerId: employerUser._id,
        status: 'pending',
        note: 'Em rảnh các buổi tối trong tuần từ 18h.',
      },
      {
        studentId: studentUser._id,
        studentName: 'Nguyễn Minh Khoa',
        studentPhone: '0981234567',
        studentEmail: 'khoa.nguyen@student.fpt.edu.vn',
        jobId: addedJobs[4]._id, // Lotteria
        employerId: employerUser._id,
        status: 'rejected',
        note: 'Em ứng tuyển ca sáng Chủ Nhật.',
        employerNote: 'Hiện quán đã đủ nhân sự ca sáng Chủ Nhật, cảm ơn em đã quan tâm.',
      },
      {
        studentId: studentUser2._id,
        studentName: 'Trần Thị Linh',
        studentPhone: '0977654321',
        studentEmail: 'linh.tran@student.fpt.edu.vn',
        jobId: j2._id,
        employerId: employerUser2._id,
        status: 'accepted',
        note: 'Em học KTX ĐHQG, đi xe buýt 72 rất tiện qua SV Market.',
        employerNote: 'Chào mừng em tham gia đội ngũ thu ngân.',
      },
      {
        studentId: studentUser2._id,
        studentName: 'Trần Thị Linh',
        studentPhone: '0977654321',
        studentEmail: 'linh.tran@student.fpt.edu.vn',
        jobId: addedJobs[0]._id, // Mixue
        employerId: employerUser._id,
        status: 'accepted',
        note: 'Em từng có kinh nghiệm làm trà sữa tại quán gần nhà.',
        employerNote: 'Nhận ca tối nhé em, nhớ mặc đồng phục quán cấp.',
      },
      {
        studentId: studentUser2._id,
        studentName: 'Trần Thị Linh',
        studentPhone: '0977654321',
        studentEmail: 'linh.tran@student.fpt.edu.vn',
        jobId: addedJobs[1]._id, // The Alley
        employerId: employerUser2._id,
        status: 'pending',
        note: 'Em có thể làm ca trưa hoặc ca tối cuối tuần.',
      },
      {
        studentId: studentUser2._id,
        studentName: 'Trần Thị Linh',
        studentPhone: '0977654321',
        studentEmail: 'linh.tran@student.fpt.edu.vn',
        jobId: addedJobs[12]._id, // Lẩu nướng BBQ
        employerId: employerUser._id,
        status: 'pending',
        note: 'Em chăm chỉ, nhanh nhẹn, có thể làm tiệc tối thứ 6, 7.',
      }
    ]);

    // 9. Reviews (Đánh giá & Uy tín)
    await Review.create([
      {
        reviewerId: employerUser._id,
        reviewerName: 'Anh Hoàng - Quản lý Café Xanh',
        reviewerRole: 'employer',
        targetId: studentUser._id,
        storeName: 'Café Xanh Hòa Lạc',
        rating: 5,
        type: 'received',
        tags: ['Đúng giờ', 'Chăm chỉ', 'Pha chế khéo tay'],
        comment: 'Bạn Khoa làm việc rất đúng giờ, pha chế nhanh nhẹn và luôn chủ động dọn dẹp quầy bar sạch sẽ trước khi giao ca.',
      },
      {
        reviewerId: employerUser2._id,
        reviewerName: 'Chị Mai - Trưởng quầy SV Market',
        reviewerRole: 'employer',
        targetId: studentUser._id,
        storeName: 'Bách Hóa SV Market',
        rating: 5,
        type: 'received',
        tags: ['Trung thực', 'Nhanh nhẹn', 'Thái độ tốt'],
        comment: 'Khoa tính tiền chuẩn xác, không bị lệch quỹ bao giờ. Rất có trách nhiệm với công việc quầy thu ngân.',
      },
      {
        reviewerId: studentUser._id,
        reviewerName: 'Nguyễn Minh Khoa',
        reviewerRole: 'student',
        targetId: employerUser._id,
        storeName: 'Café Xanh Hòa Lạc',
        rating: 5,
        type: 'given',
        tags: ['Chủ quán tâm lý', 'Trả lương đúng hẹn', 'Môi trường tốt'],
        comment: 'Chủ quán Café Xanh rất thân thiện, luôn hỗ trợ sinh viên đổi ca linh hoạt khi có lịch thi gấp. Lương tính đúng ngày mùng 5 hàng tháng.',
      },
      {
        reviewerId: studentUser._id,
        reviewerName: 'Nguyễn Minh Khoa',
        reviewerRole: 'student',
        targetId: employerUser2._id,
        storeName: 'Bách Hóa SV Market',
        rating: 5,
        type: 'given',
        tags: ['Môi trường văn minh', 'Hỗ trợ ăn nhẹ'],
        comment: 'Bách hóa SV Market quản lý chuyên nghiệp, có điều hòa mát mẻ, được giảm giá 15% khi mua đồ sinh hoạt.',
      },
      {
        reviewerId: employerUser2._id,
        reviewerName: 'Chị Mai - Trưởng quầy SV Market',
        reviewerRole: 'employer',
        targetId: studentUser2._id,
        storeName: 'Bách Hóa SV Market',
        rating: 5,
        type: 'received',
        tags: ['Dễ thương', 'Niềm nở', 'Đúng giờ'],
        comment: 'Linh giao tiếp với khách hàng rất khéo léo, khách ai cũng khen nhân viên quầy tươi cười thân thiện.',
      },
      {
        reviewerId: employerUser._id,
        reviewerName: 'Anh Hoàng - Quản lý Café Xanh',
        reviewerRole: 'employer',
        targetId: studentUser2._id,
        storeName: 'Trà Sữa Mixue Tân Xã',
        rating: 5,
        type: 'received',
        tags: ['Nhanh nhẹn', 'Sạch sẽ'],
        comment: 'Bạn học việc pha trà sữa và lấy kem ốc quế rất nhanh. Tác phong làm việc chuẩn mực.',
      },
      {
        reviewerId: studentUser2._id,
        reviewerName: 'Trần Thị Linh',
        reviewerRole: 'student',
        targetId: employerUser2._id,
        storeName: 'Bách Hóa SV Market',
        rating: 5,
        type: 'given',
        tags: ['Đồng nghiệp thân thiện', 'Lương chuẩn'],
        comment: 'Làm việc ở SV Market rất vui, các anh chị chỉ bảo tận tình từ ngày đầu tiên.',
      },
      {
        reviewerId: studentUser2._id,
        reviewerName: 'Trần Thị Linh',
        reviewerRole: 'student',
        targetId: employerUser._id,
        storeName: 'Trà Sữa Mixue Tân Xã',
        rating: 5,
        type: 'given',
        tags: ['Trà sữa ngon', 'Chủ quán tốt tính'],
        comment: 'Quán đông khách nhưng không khí làm việc luôn tràn đầy năng lượng, có trà sữa uống giữa ca.',
      }
    ]);

    console.log('[Seed] Database successfully populated with initial data!');
    process.exit(0);
  } catch (err) {
    console.error('[Seed] Error:', err);
    process.exit(1);
  }
}

seed();

